trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  group: swa-secrets-dev 
  buildDir: 'dist'  # Vite outputs to dist
  
steps:
  - task: UseNode@1
    inputs:
      version: '22.x'
    displayName: 'Use Node.js 22'

  - script: |
      npm ci
    displayName: 'Install dependencies'

  - script: |
      npx vite build
    displayName: 'Build app using Vite'

  - task: CopyFiles@2
    inputs:
      SourceFolder: '$(buildDir)'  # <- 'dist'
      Contents: '**'
      TargetFolder: '$(Build.ArtifactStagingDirectory)'
    displayName: 'Copy built files to staging'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'drop'
      publishLocation: 'Container'
    displayName: 'Publish build artifacts'

  - task: AzureStaticWebApp@0
    inputs:
      app_location: '.' # root of your Vite app
      api_location: '' # no API folder 
      output_location: '$(buildDir)'             # Vite build output folder
      azure_static_web_apps_api_token:'$(SWA_DEPLOYMENT_TOKEN_WEB_DEV)'
    displayName: 'Deploy to Azure Static Web App'
