// API Configuration
export const API_BASE_URL = import.meta.env.VITE_API_BASE_URL || 
  'https://easyhmsapi-b2fpcsh4cpbafxf0.centralindia-01.azurewebsites.net';

// API Endpoints
export const API_ENDPOINTS = {
  AUTH: {
    LOGIN: '/auth/user/login',
    SEND_OTP: 'auth/otp/send',
    SIGN_UP: '/auth/user/register',
    ONBOARDING_REGISTER: '/auth/user/onboarding/register',
    OTP_CHECKER: '/auth/otp/verify',    
    SET_PASSWORD: '/auth/user/password?scope=set-password',
    RESET_PASSWORD: '/auth/user/password?scope=reset-password',
  },
  USER: {    
    PERMISSIONS: '/user/permissions',
    GET_DETAILS: (userId: string) => `/user/get-user-details?userId=${userId}`,
    UPDATE_DETAILS: '/user/update-user-details',
    PROFILE_PHOTO: {
      UPLOAD: '/user/profile/photo/upload',
      FINALIZE: '/user/profile/photo/finalize',
      DELETE: '/user/profile/photo',
    },
  },
  HOSPITALS: {
    REGISTER: '/hospitals/register',
    GET_BY_ID: (id: string) => `/hospitals/${id}`,
    GET_BY_USER_ID: (userId: string) => `/hospitals/users/${userId}`,
  },
  DEPARTMENTS: {
    GLOBAL: '/departments/global',
  },
  SPECIALIZATIONS: {
    BY_DEPARTMENT: '/doctors/specializations',
  },
  DOCTORS: {
    PROFILE: '/doctors',
    GET_ALL: '/doctors',
    GET_BY_ID: (id: string) => `/doctors/${id}`,
    CREATE: '/doctors',
    UPDATE: (id: string) => `/doctors/${id}`,
    DELETE: (id: string) => `/doctors/${id}`,
    GET_PROFILE: '/doctors/profile',
    UPDATE_PROFILE: '/doctors/profile',
    SEARCH: (query: string) => `/doctors/search?q=${encodeURIComponent(query)}`,
    GET_STATS: '/doctors/stats',
    GET_SCHEDULE: (id: string, date: string) => `/doctors/${id}/schedule/${date}`,
    UPDATE_SCHEDULE: (id: string) => `/doctors/${id}/schedule`,
    GET_APPOINTMENTS: (id: string, params: string) => `/doctors/${id}/appointments?${params}`,
    GET_TODAY_APPOINTMENTS: '/doctors/appointments/today',
    GET_PATIENTS: (id: string) => `/doctors/${id}/patients`,
    CREATE_PRESCRIPTION: '/doctors/prescriptions',
    GET_PRESCRIPTIONS: (params: string) => `/doctors/prescriptions?${params}`,
    UPDATE_PRESCRIPTION: (id: string) => `/doctors/prescriptions/${id}`,
    DELETE_PRESCRIPTION: (id: string) => `/doctors/prescriptions/${id}`,
    GET_DASHBOARD: '/doctors/dashboard',
    UPDATE_AVAILABILITY: '/doctors/availability',
    GET_AVAILABLE_SLOTS: (date: string) => `/doctors/available-slots/${date}`,
  },
  USER_MANAGEMENT: {
    INVITE_USER: '/admin/user-onboarding/invitations?scope=new',
    GET_INVITED_USERS: '/admin/user-onboarding/invitations',
    GET_ONBOARDED_USERS: '/admin/users/onboarded',
    GET_ALL_USERS: '/admin/user-onboarding/allusers',
    MANAGE_INVITATION: '/admin/user-onboarding/invitations/manage',
    DEACTIVATE_USER: '/admin/user-onboarding/deactivate-user',
    UPDATE_INVITED_USER: '/admin/user-onboarding/invited/Update-user',
    VALIDATE_TOKEN: '/admin/user-onboarding/validate',
  },
  APPOINTMENTS: {
    GET_ALL: '/appointments',
    GET_BY_ID: (id: string) => `/appointments/${id}`,
    CREATE: '/appointments',
    UPDATE: (id: string) => `/appointments/${id}`,
    DELETE: (id: string) => `/appointments/${id}`,
    GET_TODAY: '/appointments/today',
    GET_BY_DATE: (date: string) => `/appointments/date/${date}`,
    GET_BY_DOCTOR: (doctorId: string, params: string) => `/appointments/doctor/${doctorId}?${params}`,
    GET_BY_PATIENT: (patientId: string) => `/appointments/patient/${patientId}`,
    UPDATE_STATUS: (id: string) => `/appointments/${id}/status`,
    RESCHEDULE: (id: string) => `/appointments/${id}/reschedule`,
    CANCEL: (id: string) => `/appointments/${id}/cancel`,
    COMPLETE: (id: string) => `/appointments/${id}/complete`,
    NO_SHOW: (id: string) => `/appointments/${id}/no-show`,
    GET_SLOTS: (doctorId: string, date: string) => `/appointments/slots/${doctorId}/${date}`,
    BLOCK_SLOTS: '/appointments/block-slots',
    UNBLOCK_SLOTS: '/appointments/unblock-slots',
    GET_STATS: (params: string) => `/appointments/stats${params}`,
    SEND_REMINDER: (id: string) => `/appointments/${id}/send-reminder`,
    BULK_REMINDERS: '/appointments/bulk-reminders',
  },
  PATIENTS: {
    GET_ALL: '/patients',
    GET_BY_ID: (id: string) => `/patients/${id}`,
    CREATE: '/patients',
    UPDATE: (id: string) => `/patients/${id}`,
    DELETE: (id: string) => `/patients/${id}`,
    SEARCH: (query: string) => `/patients/search?q=${encodeURIComponent(query)}`,
    GET_STATS: '/patients/stats',
    GET_PROFILE: (id: string) => `/patients/${id}/profile`,
    UPDATE_PROFILE: (id: string) => `/patients/${id}/profile`,
    GET_MEDICAL_RECORDS: (id: string) => `/patients/${id}/medical-records`,
    CREATE_MEDICAL_RECORD: '/patients/medical-records',
    UPDATE_MEDICAL_RECORD: (id: string) => `/patients/medical-records/${id}`,
    DELETE_MEDICAL_RECORD: (id: string) => `/patients/medical-records/${id}`,
    GET_APPOINTMENTS: (id: string) => `/patients/${id}/appointments`,
    GET_BILLING: (id: string) => `/patients/${id}/billing`,
    SEND_REMINDER: (id: string) => `/patients/${id}/send-reminder`,
    BULK_REMINDERS: '/patients/bulk-reminders',
    GET_DASHBOARD: (id: string) => `/patients/${id}/dashboard`,
  },
  BILLING: {
    GET_ALL: '/bills',
    GET_BY_ID: (id: string) => `/bills/${id}`,
    CREATE: '/bills',
    UPDATE: (id: string) => `/bills/${id}`,
    DELETE: (id: string) => `/bills/${id}`,
    GET_BY_PATIENT: (patientId: string) => `/bills/patient/${patientId}`,
    GET_BY_APPOINTMENT: (appointmentId: string) => `/bills/appointment/${appointmentId}`,
    UPDATE_STATUS: (id: string) => `/bills/${id}/status`,
    CREATE_PAYMENT: '/bills/payments',
    GET_PAYMENTS: (billId: string) => `/bills/${billId}/payments`,
    CREATE_INSURANCE_CLAIM: '/bills/insurance-claims',
    GET_INSURANCE_CLAIMS: (params: string) => `/bills/insurance-claims?${params}`,
    UPDATE_INSURANCE_CLAIM_STATUS: (id: string) => `/bills/insurance-claims/${id}/status`,
    GET_STATS: (params: string) => `/bills/stats?${params}`,
    GET_CONFIGURATION: '/bills/configuration',
  },
  AI: {
    GET_CONVERSATIONS: (params: string) => `/ai/conversations?${params}`,
    GET_CONVERSATION: (id: string) => `/ai/conversations/${id}`,
    CREATE_CONVERSATION: '/ai/conversations',
    DELETE_CONVERSATION: (id: string) => `/ai/conversations/${id}`,
    GET_MESSAGES: (conversationId: string) => `/ai/conversations/${conversationId}/messages`,
    SEND_MESSAGE: '/ai/conversations/send-message',
    GET_DOCUMENT_ANALYSES: (params: string) => `/ai/document-analyses?${params}`,
    GET_DOCUMENT_ANALYSIS: (id: string) => `/ai/document-analyses/${id}`,
    CREATE_DOCUMENT_ANALYSIS: '/ai/document-analyses',
    DELETE_DOCUMENT_ANALYSIS: (id: string) => `/ai/document-analyses/${id}`,
    GET_MEDICAL_INSIGHTS: (params: string) => `/ai/medical-insights?${params}`,
    GET_MEDICAL_INSIGHT: (id: string) => `/ai/medical-insights/${id}`,
    GENERATE_MEDICAL_INSIGHT: '/ai/medical-insights/generate',
    DELETE_MEDICAL_INSIGHT: (id: string) => `/ai/medical-insights/${id}`,
    GET_ASSISTANTS: '/ai/assistants',
    GET_ASSISTANT: (id: string) => `/ai/assistants/${id}`,
    CREATE_ASSISTANT: '/ai/assistants',
    UPDATE_ASSISTANT: (id: string) => `/ai/assistants/${id}`,
    DELETE_ASSISTANT: (id: string) => `/ai/assistants/${id}`,
    GET_MODELS: '/ai/models',
    GET_MODEL: (id: string) => `/ai/models/${id}`,
    GET_STATS: (params: string) => `/ai/stats?${params}`,
    SEARCH_CONVERSATIONS: (query: string) => `/ai/conversations/search?q=${encodeURIComponent(query)}`,
    DELETE_MESSAGES: (conversationId: string) => `/ai/conversations/${conversationId}/messages`,
    GET_CONVERSATION_SUMMARY: (conversationId: string) => `/ai/conversations/${conversationId}/summary`,
    GENERATE_CONVERSATION_TITLE: (conversationId: string) => `/ai/conversations/${conversationId}/generate-title`,
    ANALYZE_MEDICAL_TEXT: '/ai/analyze-medical-text',
    GET_PATIENT_SUGGESTIONS: (patientId: string) => `/ai/patients/${patientId}/suggestions`,
    GET_DIAGNOSIS_SUGGESTIONS: '/ai/diagnosis-suggestions',
    CHECK_MEDICATION_INTERACTIONS: '/ai/medication-interactions',
  },
              CALENDAR: {
              GET_DOCTOR_TIMEOFF: (doctorId: string) => `/calendar/doctor/timeoff?doctorId=${doctorId}`,
              CREATE_DOCTOR_TIMEOFF: '/calendar/doctor/timeoff',
              DELETE_DOCTOR_TIMEOFF: (timeOffId: string) => `/calendar/doctor/timeoff/${timeOffId}`,
                  GET_DOCTOR_CONFIG: (doctorId: string, startDate: string, days: number) => `/calendar/doctor/config?doctorId=${doctorId}&startDate=${encodeURIComponent(startDate)}&daysCount=${days}`,
    CREATE_DOCTOR_OVERRIDE: '/calendar/doctor/override',
    DELETE_DOCTOR_OVERRIDE: (overrideId: string) => `/calendar/doctor/override/${overrideId}`,
            },
  MEDIA: {
    PREPARE_UPLOAD: '/media/upload-assigned-url/prepare',
    FINALIZE_UPLOAD: '/media/upload-assigned-url/finalize',
    GET_URL: '/media/get-preassigned-url',
  },
} as const;

// Default headers
export const DEFAULT_HEADERS = {
  'Content-Type': 'application/json',
} as const; 